### ISSUE TITLE
Cant upload to Hockey groups

### ISSUE THREAD

**Issue by frmz** [oliviergauthier/gradle-appcenter-plugin#16]
Not sure if its plugin related, i will try to do an upload manually, but do you know why an upload to a group imported from Hockey might fail? It works from the Appcenter UI but it fails silently from the plugin, it will just skip that group. Unfortunately there is no way to test this unless you already have an Hockey imported group and an Hockey account.

**Comment by zoltanf** [comment]
I just noticed a similar issue, make sure you use the right owner name, as it seems that apps from HockeyApp have a different owner name than the ones created in AppCenter.
