### ISSUE TITLE
Could not find com.betomorrow.gradle:appcenter-plugin:1.1.1

### ISSUE THREAD

**Issue by SOERGI** [oliviergauthier/gradle-appcenter-plugin#2]
Hi,
I get `Could not find com.betomorrow.gradle:appcenter-plugin:1.1.1` when using the line `classpath "com.betomorrow.gradle:appcenter-plugin:1.1.1"`
However `classpath "gradle.plugin.com.betomorrow.gradle:appcenter-plugin:1.1.1"` works for me. You might want to update you readme file.

Thanks

**Comment by oliviergauthier** [comment]
Thanks for this issue, i have updated readme file
