### ISSUE TITLE
Upload proguard mapping

### ISSUE THREAD

**Issue by przan** [oliviergauthier/gradle-appcenter-plugin#21]
Hi! There is no mapping.txt file uploaded to AppCenter for given .apk. Do you plan to add this?

**Comment by oliviergauthier** [comment]
I can try to add this feature, where mapping file is located by default in a standard android project ?

Thks

**Comment by przan** [comment]
It would be really great to have this, as one of the reasons to upload to appcenter is to collect crash logs, which are useless when obfuscated.

I have the mapping here: `app\build\outputs\mapping\{flavors}\release\mapping.txt`

We use 2 dimens for flavors (one for environment, e.g. test, qa, prod and one for brand, e.g. productOne, productTwo) so in our case {flavor} mentioned in the above path is e.g. productTwoQa

https://stackoverflow.com/questions/25724645/where-does-android-studio-save-the-proguard-mapping-file

**Comment by oliviergauthier** [comment]
Can you please try version 1.1.12 ? I have adde mapping file upload. Tell me if it fit your needs

Thanks

**Comment by przan** [comment]
The mapping for my app has been uploaded with correct versionCode and versionName. Thanks a lot for such quick implementation!
