### ISSUE TITLE
Set appName as environment variable

### ISSUE THREAD

**Issue by kingargyle** [oliviergauthier/gradle-appcenter-plugin#22]
I haven't been able to get appName to take an in an environment variable if it has been assigned.  I basically want to do something like.

  flavorDebug {
      appName = "${System.env.APP_NAME}"
  }

unfortunately every way I've tried, it ignores it and fails the upload.  Only hard coding the name seems to work.

**Comment by oliviergauthier** [comment]
It works with `System.getenv("APP_NAME")``

**Sample :**
```
appcenter {
    apiToken = project.properties.get("apiToken", "")
    ownerName = project.properties.get("ownerName", "")
    distributionGroups = ["Collaborators"]
    releaseNotes = "A Sample Upload"
    notifyTesters = false
    apps {
        release {
            appName = System.getenv("APP_NAME")
        }
    }
}
```

**Comment by kingargyle** [comment]
I kept trying that exact code, and for some reason it would always return null.  I'll keep checking and if I get it working or not I'll close this out.

**Comment by oliviergauthier** [comment]
can you copy both your root gradle script and your app gradle script ? Did you tried to print all env variables in your script ?

**Comment by kingargyle** [comment]
unfortunately I can't copy the copy the clients scripts here.  I'll do some more debugging today and see if I can track down the problem.  Will report back here my findings.

**Comment by kingargyle** [comment]
Closing this as I haven't had time to revisit.
