### ISSUE TITLE
App bundle

### ISSUE THREAD

**Issue by AzamatEm** [oliviergauthier/gradle-appcenter-plugin#25]
Is it possible to use this plugin to upload app bundles (.aab files)?

**Comment by oliviergauthier** [comment]
Is it possible to upload aab files with AppCenter web site ?

**Comment by AzamatEm** [comment]
@oliviergauthier, sorry, you are right. I read carefully this thread https://github.com/microsoft/fastlane-plugin-appcenter/issues/106 and it wont be even supported because it is google play exclusive feature

**Comment by perchrh** [comment]
Now app bundles are supported on the AppCenter web site. Uploaded one today.
