### ISSUE TITLE
appCenterUpload tasks assembles build

### ISSUE THREAD

**Issue by mfrtrifork** [oliviergauthier/gradle-appcenter-plugin#26]
Imagine that you have an APK which you would just like to upload. Would be nice if it was not rebuild by the upload script.

**Comment by oliviergauthier** [comment]
Hi,

I'm not sure to understand what you want. Do you want the upload task stop depends on assemble task ?

Regards

Olivier

**Comment by mfrtrifork** [comment]
Hi Olivier.

Yes, I have a complex pipeline for distributing the app where I do not have access to the keystore at buildtime.
This means that I would like to assemble an unsigned APK and then zipalign and sign the APK in next step on the clients buildserver where the keystore is accessible.
Last step on the build server would then be to simply upload the APK and the associated mapping file using your plugin.

Maybe you can expose both gradle tasks? one for assemble and upload and one for only uploading.

Regards
Michael

**Comment by oliviergauthier** [comment]
Hi Michael,

I have changed dependencies between tasks. You can now run upload tasks without rebuilding

Regards
Olivier

**Comment by mfrtrifork** [comment]
Thanks @oliviergauthier it works like a charm ;)

**Comment by konstzv** [comment]
As I understand you've reworked old tasks.
Can you keep both old and new?
