### ISSUE TITLE
Support for uploading NDK symbols.zip

### ISSUE THREAD

**Issue by jasonschroeder-sfdc** [oliviergauthier/gradle-appcenter-plugin#27]
We have an Android app with native libraries and that requires a "symbols.zip" to be uploaded. See https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#symbolication

**Comment by oliviergauthier** [comment]
I have added "symbols" configuration working like distribution group. It expected to be a liste of file or filename. Can you check if it fit your needs ?


```
appcenter {
    apiToken = project.properties.get("apiToken", "")
    ownerName = project.properties.get("ownerName", "")
    distributionGroups = ["Collaborators"]
    releaseNotes = "A Sample Upload"
    notifyTesters = false
    symbols = [ "symbols.zip" ]
    apps {
        alpha {
            dimension = "environment"
            appName = "GradleSample"
        }
        beta {
            dimension = "environment"
            appName = "GradleSample"
        }
    }
}
```

Thanks

**Comment by jasonschroeder-sfdc** [comment]
Thank you so much @oliviergauthier , we will check it out today!

**Comment by JiaYangSF** [comment]
Hello @oliviergauthier, I followed your suggestion, but still didn't see symbols file being uploaded. I wonder if the symbols file needs to be in a specific dir for the plugin to identify it? Can you show me the symbols.zip location?
