### ISSUE TITLE
Cannot split by ABI filters

### ISSUE THREAD

**Issue by Jacks0N23** [oliviergauthier/gradle-appcenter-plugin#28]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':ui'.
Cannot add task 'appCenterUploadActualBackendQa' as a task with that name already exists.

CONFIGURE FAILED in 1s
Cannot add task 'appCenterUploadActualBackendQa' as a task with that name already exists.

My splits configuration
```    
splits {
        abi {
            enable true
            reset()
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            universalApk false
        }
    }
```

**Comment by oliviergauthier** [comment]
Does @konstzv PR works for you ?

Thanks

**Comment by bvschaik** [comment]
We also encountered this issue. Upgrading from 1.1.16 to 1.1.17 fixed the issue.
