### ISSUE TITLE
Unable to skip mapping.txt upload

### ISSUE THREAD

**Issue by SagarBegale** [oliviergauthier/gradle-appcenter-plugin#38]
We want to avoid uploading `mapping.txt` file to app center. Is there any way to achieve it?

**Comment by oliviergauthier** [comment]
You can already do that but it's not documented. Use property `uploadMappingFiles = false` in your appCenter or app configuration in build.gradle

**Comment by SagarBegale** [comment]
I got the following error:
```
Could not set unknown property 'uploadMappingFiles' for object of type com.betomorrow.gradle.appcenter.extensions.AppCenterAppExtension
```

I added it under:

```
release {
    uploadMappingFiles = false
    ...
}
```

**Comment by konstzv** [comment]
Do you use the latest version?

**Comment by SagarBegale** [comment]
Thank you for quick response. I was using `1.1.16`. After upgrading to `1.1.17` our build works.
