### ISSUE TITLE
Multi Dimensions

### ISSUE THREAD

**Issue by bironader** [oliviergauthier/gradle-appcenter-plugin#65]
I can not  figure how can I upload variants with multi dimensions

example if i have two dimensions     `flavorDimensions "client", "environment"`

```
     stage {
            dimension "environment"
            applicationIdSuffix ".stage"
        }

     development {
            dimension "environment"
            applicationIdSuffix ".development"
        }
     production {
            dimension "environment"
            applicationIdSuffix ".production"
        }
        
     A {
            dimension "client"
        }
     B {
            dimension "client"
        }
     C {
            dimension "client"
        }
     D {
            dimension "client"
        }


how can I build APK for all client with stage flavor and all client with development flavor
```

**Comment by oliviergauthier** [comment]
Hi,

I'm not sur to understand what your are trying to do but i think you can configure plugin with environment dimension, it will generate all clients tasks or you can declare directly the full variant name :  AStageRelease, BStageRelease etc without setting dimension

Regards 

Olivier
