### ISSUE TITLE
Upload to App Center fails with error 400

### ISSUE THREAD

**Issue by gmbett** [oliviergauthier/gradle-appcenter-plugin#69]
Since yesterday uploads to App center started to fail with the following error:

Can't prepare release upload, code=400, reason={"error":{"code":400,"message":"One or more invalid parameters:\nParameter file_size must be greater than 0 : 0"}}

Note: The upload was working perfectly fine before. I even tried to update to version 1.3.0 but I'm still getting the same error

**Comment by gmbett** [comment]
Found the root cause of the problem, is not on your side. My bad.

**Comment by lazarpanchevski** [comment]
> Found the root cause of the problem, is not on your side. My bad.

I'm getting the same error,
`Can't prepare release upload, code=400, reason={"error":{"code":400,"message":"One or more invalid parameters:\nParameter file_size must be greater than 0 : 0"}}`

Can you describe please what is the fix for this?

**Comment by gmbett** [comment]
I was trying to upload an .apk that was not "available" (not built yet)

**Comment by petersanta** [comment]
Hi, I got a similar error since yesterday with 1.2.1
`Can't prepare release upload, code=400, reason={"status":400,"name":"Error","message":"Missing required body parameter \"body\""}`

When I update to 1.3.0, I get the same error as gmbett or lazarpanchevski.

**Comment by swiatlow** [comment]
Hi, same issue for me:
`Can't prepare release upload, code=400, reason={"status":400,"name":"Error","message":"Missing required body parameter \"body\""}`
`POST https://api.appcenter.ms/v0.1/apps/williamhill/Android-Games-Debug/release_uploads (0-byte body)`

Is it maybe connected with the fact that endpoint is deprecated on AppCenter API?
[](https://openapi.appcenter.ms/#/distribute/releaseUploads_create)
