### ISSUE TITLE
Can't prepare release upload, code=404

### ISSUE THREAD

**Issue by adarzulfu** [oliviergauthier/gradle-appcenter-plugin#70]
The issue has been started, Can not push apk to appcenter
 
 Can't prepare release upload, code=404, reason={"message":"Resource not found: /v0.1/apps///release_uploads. Correlation ID: 5737e0d5-edc2-4955-9f51-a22f9dae3273","statusCode":404,"code":"Not Found"}

**Comment by maras93** [comment]
@adarzulfu Did you update plugin to the newest version 1.3.0?

**Comment by adarzulfu** [comment]
updated and the problem seems fixed. Thank you.
