### ISSUE TITLE
appCenter gradle tasks not visible

### ISSUE THREAD

**Issue by ewoks** [oliviergauthier/gradle-appcenter-plugin#8]
Included plugin by adding following to the app/build.gradle as stated [here](https://plugins.gradle.org/plugin/com.betomorrow.appcenter):
`plugins {
  id "com.betomorrow.appcenter" version "1.1.4"
}`

Not sure if readme is missing something or something is broken but after gradle sync, I can't see any new tasks when trying with:
`./gradlew tasks | grep appCenter`

In which group new tasks should appear?

**Comment by ewoks** [comment]
My bad :/
Dimension was missing for both flavors nor I added "Release" after flavor name.

**Comment by maverickabhi1991** [comment]
@ewoks : Can you please share the line of code that shows the usage of "appCenterUploadBetaRelease"
I need to call something like this:
appCenterUploadBetaRelease.dependsOn runMsBuild
Thanks!!!
