### ISSUE TITLE
Upload to AppCenter failing after updating Kotlin

### ISSUE THREAD

**Issue by cjuneja** [oliviergauthier/gradle-appcenter-plugin#84]
hi there,
I have noticed that upload to AppCenter using this plugin is failing after I updated the kotlin to 1.5.30. 

using plugin 1.3.0 

Error 
error	18-Mar-2022 22:03:54	Execution failed for task ':app:appCenterUploadApkBeta'.
error	18-Mar-2022 22:03:54	> com.betomorrow.gradle.appcenter.infra.AppCenterUploaderException: Can't prepare release upload, code=404, reason={"message":"Not found. Correlation ID: 12d53ab7-d745-46ed-8ba9-d481e7dc1ec0","statusCode":404,"code":"Not Found"}

any help would be appreciated! thanks!

**Comment by victorlsn** [comment]
I'm having the same issue here!

**Comment by cjuneja** [comment]
I have moved my android builds to bitrise where uploading to App center
works fine. Might say it was not too difficult to do. GOod luck!
