### ISSUE TITLE
[Suggestion] Get Appcenter link to the distribution as output

### ISSUE THREAD

**Issue by ege-ah** [oliviergauthier/gradle-appcenter-plugin#89]
would be nice to get the link or atleast the id to the distribution as output so we can save time on CI while providing it to the testers. Similar to fastlane plugin for Appcenter: https://github.com/microsoft/fastlane-plugin-appcenter/issues/49

**Comment by mobiRic** [comment]
It seems like this issue can be closed as the functionality exists on 2.0.4 at the end of the gradle task output.

```
> Task :app:appCenterUploadApk...Debug
AppCenter release url is https://appcenter.ms/orgs/.../apps/.../distribute/releases/...
```
