### ISSUE TITLE
Add a way to cut release notes

### ISSUE THREAD

**Issue by gmbett** [oliviergauthier/gradle-appcenter-plugin#9]
It seems App Center has a max limit of 5000 characters for release notes:

> Can't distribute release, code=400, reason={"code":"bad_request","message":"Error: The release notes exceeds the limit of 5000 characters."}

Can you add a flag to truncate it ?

**Comment by oliviergauthier** [comment]
Fixed in 1.1.5

**Comment by gmbett** [comment]
Thanks!
